BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-nano \
    arduino-uno \
    atmega328p \
    atmega328p-xplained-mini \
    bluepill-stm32f030c8 \
    im880b \
    nucleo-l011k4 \
    olimexino-stm32 \
    samd10-xmini \
    slstk3400a \
    stk3200 \
    zigduino \
    #
