# peripheral drivers are linked into the final binary
USEMODULE += atxmega_periph

# All ATxmega based CPUs provide PM
USEMODULE += pm_layered

ifeq (,$(filter cpuid,$(USEMODULE)))
  USEMODULE += periph_nvm
endif

ifeq (,$(filter periph_usbdev,$(USEMODULE)))
  USEMODULE += periph_nvm periph_clock
endif

include $(RIOTCPU)/avr8_common/Makefile.dep
